/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmgtpackage;

import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author bulouere
 */
public class ForgotPassword2 extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword2
     */
    public ForgotPassword2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.  
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        secretWord = new javax.swing.JTextField();
        enter_ForgotPassword = new javax.swing.JButton();
        signIn_ForgotPassword = new javax.swing.JLabel();
        signUp_ForgotPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("FORGOT PASSWORD");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1006, 90));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("Username:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        username.setBackground(new java.awt.Color(204, 255, 204));
        username.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel2.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 190, 30));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Secret Word:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 30));

        secretWord.setBackground(new java.awt.Color(204, 255, 204));
        secretWord.setFont(new java.awt.Font("Georgia", 0, 16)); // NOI18N
        jPanel2.add(secretWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 190, 30));

        enter_ForgotPassword.setBackground(new java.awt.Color(204, 255, 204));
        enter_ForgotPassword.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        enter_ForgotPassword.setForeground(new java.awt.Color(0, 0, 102));
        enter_ForgotPassword.setText("Enter");
        enter_ForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enter_ForgotPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(enter_ForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 560, 250));

        signIn_ForgotPassword.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        signIn_ForgotPassword.setText("Already have an account? Click here to sign in");
        signIn_ForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signIn_ForgotPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(signIn_ForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        signUp_ForgotPassword.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        signUp_ForgotPassword.setText("Don't have account? Click here to register");
        signUp_ForgotPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUp_ForgotPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(signUp_ForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1006, 501));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    PreparedStatement pst;
    ResultSet rs;
    private void enter_ForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enter_ForgotPasswordActionPerformed
        //get username and secretword inputs
        String secretWordString = secretWord.getText();
        String usernameString = username.getText();
        
        //get username and password from database with username or secretword inputed by user
        String query = "SELECT name, password FROM Admin_RegForm WHERE name = " + "'" + usernameString + "' "
                            + "OR SecretWord = " + "'" + secretWordString + "'";
        try {
            pst = MySqlConnection.getConnection().prepareStatement(query);
            rs = pst.executeQuery();
                if (rs.next()) {
                    String usernameDb = rs.getString("name");
                    String passwordDb = rs.getString("password");
                        
                    //check if secretword or username match anything record in database
                    JOptionPane.showMessageDialog(null, "Username: "+usernameDb+"\n Password: "+passwordDb);
                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect username or secret word");
                }
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_enter_ForgotPasswordActionPerformed

    private void signIn_ForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signIn_ForgotPasswordMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signIn_ForgotPasswordMouseClicked

    private void signUp_ForgotPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUp_ForgotPasswordMouseClicked
        signUp_ForgotPassword.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.dispose();
        RegForm regForm = new RegForm();
        regForm.setVisible(true);
    }//GEN-LAST:event_signUp_ForgotPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter_ForgotPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField secretWord;
    private javax.swing.JLabel signIn_ForgotPassword;
    private javax.swing.JLabel signUp_ForgotPassword;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
