/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmgtpackage;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Iredafe
 */
public class RegForm extends javax.swing.JFrame {

    /**
     * Creates new form RegForm
     */
        //create a function to check if username already exists in database
        //       public boolean checkUsername(String Username){

    

    // }
    //center form
    public RegForm() {
        initComponents();

        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        secretword = new javax.swing.JTextField();
        jPasswd = new javax.swing.JPasswordField();
        btnReg = new javax.swing.JButton();
        jConfirmPwd1 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        loginLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(102, 102, 255), null, null));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Enter a Secret Word");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 280, 50));

        jLabel3.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Name");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 50));

        jLabel4.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, 50));

        secretword.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.add(secretword, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 190, 30));

        jPasswd.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.add(jPasswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 190, 30));

        btnReg.setBackground(new java.awt.Color(204, 255, 204));
        btnReg.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        btnReg.setForeground(new java.awt.Color(0, 0, 102));
        btnReg.setText("SIGN UP");
        btnReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegMouseClicked(evt);
            }
        });
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });
        jPanel3.add(btnReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, -1));

        jConfirmPwd1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.add(jConfirmPwd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 190, 30));

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Confirm Password");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 280, 50));

        nameField.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 190, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 560, 330));

        loginLabel.setFont(new java.awt.Font("Book Antiqua", 0, 16)); // NOI18N
        loginLabel.setText("Already have an account? Click here to Sign in.");
        loginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginLabelMouseClicked(evt);
            }
        });
        jPanel1.add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 360, -1));

        jLabel6.setFont(new java.awt.Font("Book Antiqua", 0, 18)); // NOI18N
        jLabel6.setText("Kindly choose your designation and fill the form to Sign Up");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 490, -1));

        jComboBox.setBackground(new java.awt.Color(153, 255, 153));
        jComboBox.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jComboBox.setForeground(new java.awt.Color(204, 255, 204));
        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Admin", "Sales", "Account", "All Privileges" }));
        jComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 88, 1050, 440));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("REGISTER HERE");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 450, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stockmgtpackage/icons/logo3.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 120, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 1050, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegMouseClicked

       /* give the sign up/register button instructions to send users details to database
        *use if statements to check if user entry for passwords & confirm password fields match
        *if the passwords match, the query in the try block executes, if they do not match the 
        *else statement in the catch block executes*/
    


   String name = nameField.getText();
        String secret_word = secretword.getText();
        String pwd = String.valueOf(jPasswd.getPassword());
        String cpwd = String.valueOf(jConfirmPwd1.getPassword());

        
//        if(jComboBox.getSelectedItem().toString().equals(switch(jComboBox.getSelectedItem().toString()))){
            
            
            
  //      }
        
                        //use a function to ensure that the user inputs the right values
                if (name.trim().equals("") || pwd.trim().equals("") || cpwd.trim().equals("") || secret_word.trim().equals("")) {
                    
                    JOptionPane.showMessageDialog(null, "One or more Fields are Empty", "Empty Fields",2);
                   
                }else{
 
        if (pwd.equals(cpwd)) {

            PreparedStatement pmst;

            try {
                String query = "INSERT INTO `StockMGT_DB`.`Admin_RegForm`"
                        + "(`name`,`password`,secret_word)"
                        + "VALUES(?,?,?);";

                pmst = MySqlConnection.getConnection().prepareStatement(query);

                pmst.setString(1, name);
                pmst.setString(2, pwd);
                pmst.setString(3, secret_word);

                if (pmst.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Registered Successfully! \n");
                    this.dispose();
                
                } else {
                    JOptionPane.showMessageDialog(null, "Registration Failed! \n");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);


            }
        } else {
            JOptionPane.showMessageDialog(null, "Password and confirm password fields do not match");

        }

    }//GEN-LAST:event_btnRegMouseClicked
    }
    private void loginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginLabelMouseClicked
        this.dispose();
//Login log= new Login();
//log.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_loginLabelMouseClicked

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed

    }//GEN-LAST:event_btnRegActionPerformed

    private void jComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxActionPerformed

        String name = nameField.getText();
        String secret_word = secretword.getText();
        String pwd = String.valueOf(jPasswd.getPassword());
        String cpwd = String.valueOf(jConfirmPwd1.getPassword());

                        //use a function to ensure that the user inputs the right values

    
        switch (jComboBox.getSelectedItem().toString()){
          
            case "admin":  
     if (name.trim().equals("") || pwd.trim().equals("") || cpwd.trim().equals("") || secret_word.trim().equals("")) {
                    
                    JOptionPane.showMessageDialog(null, "One or more Fields are Empty", "Empty Fields",2);
                   
                }else{
 
        if (pwd.equals(cpwd)) {

            PreparedStatement pmst;

            try {
                String query = "INSERT INTO `StockMGT_DB`.`Admin_RegForm`"
                        + "(`name`,`password`,secret_word)"
                        + "VALUES(?,?,?);";

                pmst = MySqlConnection.getConnection().prepareStatement(query);

                pmst.setString(1, name);
                pmst.setString(2, pwd);
                pmst.setString(3, secret_word);

                if (pmst.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Registered Successfully! \n");
                    this.dispose();
                
                } else {
                    JOptionPane.showMessageDialog(null, "Registration Failed! \n");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);


            }
        } else {
            JOptionPane.showMessageDialog(null, "Password and confirm password fields do not match");

        }

    }              
               break;
               
               
          case "sales":
     if (name.trim().equals("") || pwd.trim().equals("") || cpwd.trim().equals("") || secret_word.trim().equals("")) {
                    
                    JOptionPane.showMessageDialog(null, "One or more Fields are Empty", "Empty Fields",2);
                   
                }else{
 
        if (pwd.equals(cpwd)) {

            PreparedStatement pmst;

            try {
                String query = "INSERT INTO `StockMGT_DB`.`sales_regform`"
                        + "(`name`,`password`,secret_word)"
                        + "VALUES(?,?,?);";

                pmst = MySqlConnection.getConnection().prepareStatement(query);

                pmst.setString(1, name);
                pmst.setString(2, pwd);
                pmst.setString(3, secret_word);

                if (pmst.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Registered Successfully! \n");
                    this.dispose();
                
                } else {
                    JOptionPane.showMessageDialog(null, "Registration Failed! \n");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);


            }
        } else {
            JOptionPane.showMessageDialog(null, "Password and confirm password fields do not match");

        }

    }                         
                  break;
                  
          case "account":
     if (name.trim().equals("") || pwd.trim().equals("") || cpwd.trim().equals("") || secret_word.trim().equals("")) {
                    
                    JOptionPane.showMessageDialog(null, "One or more Fields are Empty", "Empty Fields",2);
                   
                }else{
 
        if (pwd.equals(cpwd)) {

            PreparedStatement pmst;

            try {
                String query = "INSERT INTO `StockMGT_DB`.`account_regform`"
                        + "(`name`,`password`,secret_word)"
                        + "VALUES(?,?,?);";

                pmst = MySqlConnection.getConnection().prepareStatement(query);

                pmst.setString(1, name);
                pmst.setString(2, pwd);
                pmst.setString(3, secret_word);

                if (pmst.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Registered Successfully! \n");
                    this.dispose();
                
                } else {
                    JOptionPane.showMessageDialog(null, "Registration Failed! \n");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);


            }
        } else {
            JOptionPane.showMessageDialog(null, "Password and confirm password fields do not match");

        }

    }               
                  break;
                  
          case "all_privileges":
     if (name.trim().equals("") || pwd.trim().equals("") || cpwd.trim().equals("") || secret_word.trim().equals("")) {
                    
                    JOptionPane.showMessageDialog(null, "One or more Fields are Empty", "Empty Fields",2);
                   
                }else{
 
        if (pwd.equals(cpwd)) {

            PreparedStatement pmst;

            try {
                String query = "INSERT INTO `StockMGT_DB`.`all_privileges`"
                        + "(`name`,`password`,secret_word)"
                        + "VALUES(?,?,?);";

                pmst = MySqlConnection.getConnection().prepareStatement(query);

                pmst.setString(1, name);
                pmst.setString(2, pwd);
                pmst.setString(3, secret_word);

                if (pmst.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "Registered Successfully! \n");
                    this.dispose();
                
                } else {
                    JOptionPane.showMessageDialog(null, "Registration Failed! \n");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);


            }
        } else {
            JOptionPane.showMessageDialog(null, "Password and confirm password fields do not match");

        }

    }             
                  
                  break;
                  
        default: 
            
            JOptionPane.showMessageDialog(null, "Select your designation in order to be Registered!");
           
                  }
    
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReg;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JPasswordField jConfirmPwd1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswd;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField secretword;
    // End of variables declaration//GEN-END:variables
}
