/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stockmgtpackage.icons;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.LayoutManager;
import javafx.scene.chart.Chart;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;
import stockmgtpackage.MySqlConnection;

/**
 *
 * @author Iredafe
 */
public class NewJFrameTest extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameTest
     */
    public NewJFrameTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topDashboard = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        leftDashboard = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        subTopDashboard = new javax.swing.JPanel();
        settingsInSubTopPanel = new javax.swing.JLabel();
        jTabbedPaneForTeacherDshboard = new javax.swing.JTabbedPane();
        lecturePanel = new javax.swing.JPanel();
        jTabbedPaneForLectureBtn = new javax.swing.JTabbedPane();
        addSubjectPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        uploadVideoPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        addToLibraryPanel = new javax.swing.JPanel();
        updateSubjectPanel = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton15 = new javax.swing.JButton();
        schedulePanel = new javax.swing.JPanel();
        assessmentPanel = new javax.swing.JPanel();
        examsPanel = new javax.swing.JPanel();
        gradesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topDashboard.setBackground(new java.awt.Color(0, 102, 102));
        topDashboard.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        topDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        topDashboard.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 150, 40));
        topDashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 10, 40, 40));

        getContentPane().add(topDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1210, 80));

        leftDashboard.setBackground(new java.awt.Color(0, 102, 102));
        leftDashboard.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        leftDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton2.setText("Assessment");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftDashboard.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 110, 70));

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton3.setText("Exams");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftDashboard.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 110, 70));

        jButton4.setBackground(new java.awt.Color(153, 255, 153));
        jButton4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton4.setText("Grades");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftDashboard.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 110, 70));

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton5.setText("Lecture");
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftDashboard.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 70));

        jButton7.setBackground(new java.awt.Color(153, 255, 153));
        jButton7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton7.setText("Schedule");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        leftDashboard.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 70));

        getContentPane().add(leftDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 200, 570));

        subTopDashboard.setBackground(new java.awt.Color(0, 153, 153));
        subTopDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        subTopDashboard.add(settingsInSubTopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 40, 40));

        getContentPane().add(subTopDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 1010, 50));

        lecturePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addSubjectPanel.setBackground(new java.awt.Color(153, 255, 153));
        addSubjectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel2.setText("Lecture Notes");
        addSubjectPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 20));

        jButton6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton6.setText("Upload");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        addSubjectPanel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jButton10.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton10.setText("Preview");
        addSubjectPanel.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 380, -1, -1));

        jTextField2.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        addSubjectPanel.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, 40));

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel4.setText("Topics");
        addSubjectPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel5.setText("Notes");
        addSubjectPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 40, 20));

        jLabel6.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel6.setText("Topics");
        addSubjectPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel7.setText("Subject Name");
        addSubjectPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 20));
        addSubjectPanel.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 150, 40));

        jButton11.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton11.setText("Update Subject");
        addSubjectPanel.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        jPanel9.setBackground(new java.awt.Color(255, 255, 153));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        addSubjectPanel.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 450, 280));

        jButton13.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton13.setText("Add Subject");
        addSubjectPanel.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 380, 120, -1));

        jTabbedPaneForLectureBtn.addTab("tab1", addSubjectPanel);

        uploadVideoPanel.setBackground(new java.awt.Color(153, 255, 153));
        uploadVideoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel3.setText("Lecture Videos");
        uploadVideoPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        uploadVideoPanel.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 100, 30));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 2));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        uploadVideoPanel.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 360, 220));

        jButton8.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton8.setText("Upload");
        uploadVideoPanel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, -1, -1));

        jButton18.setBackground(new java.awt.Color(0, 102, 102));
        jButton18.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton18.setText("Back To Home");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, -1, 30));

        jButton9.setBackground(new java.awt.Color(0, 102, 102));
        jButton9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton9.setText("Watch Videos");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, -1, 30));

        jButton12.setBackground(new java.awt.Color(0, 102, 102));
        jButton12.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton12.setText("e-Library ");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        uploadVideoPanel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 100, 30));

        jTabbedPaneForLectureBtn.addTab("tab2", uploadVideoPanel);

        addToLibraryPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPaneForLectureBtn.addTab("tab3", addToLibraryPanel);

        updateSubjectPanel.setBackground(new java.awt.Color(153, 255, 153));
        updateSubjectPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        updateSubjectPanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 150, 30));

        jLabel8.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel8.setText("Update Videos");
        updateSubjectPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, -1, 20));

        jLabel9.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel9.setText("Select Subject:");
        updateSubjectPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, 20));

        jLabel10.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel10.setText("Update Topic");
        updateSubjectPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jTextField4.setText("jTextField4");
        updateSubjectPanel.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 140, 30));

        jButton14.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton14.setText("Upload");
        updateSubjectPanel.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, -1, -1));

        jLabel11.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jLabel11.setText("Update Notes");
        updateSubjectPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        updateSubjectPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 340, 250));

        jButton15.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        jButton15.setText("Upload");
        updateSubjectPanel.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jTabbedPaneForLectureBtn.addTab("tab4", updateSubjectPanel);

        lecturePanel.add(jTabbedPaneForLectureBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 1010, 510));

        jTabbedPaneForTeacherDshboard.addTab("tab1", lecturePanel);
        jTabbedPaneForTeacherDshboard.addTab("tab2", schedulePanel);
        jTabbedPaneForTeacherDshboard.addTab("tab3", assessmentPanel);

        examsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPaneForTeacherDshboard.addTab("tab4", examsPanel);

        gradesPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jTabbedPaneForTeacherDshboard.addTab("tab5", gradesPanel);

        getContentPane().add(jTabbedPaneForTeacherDshboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 1010, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        dispose();
        StudentHome sh = new StudentHome();
        sh.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addSubjectPanel;
    private javax.swing.JPanel addToLibraryPanel;
    private javax.swing.JPanel assessmentPanel;
    private javax.swing.JPanel examsPanel;
    private javax.swing.JPanel gradesPanel;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPaneForLectureBtn;
    private javax.swing.JTabbedPane jTabbedPaneForTeacherDshboard;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPanel lecturePanel;
    private javax.swing.JPanel leftDashboard;
    private javax.swing.JPanel schedulePanel;
    private javax.swing.JLabel settingsInSubTopPanel;
    private javax.swing.JPanel subTopDashboard;
    private javax.swing.JPanel topDashboard;
    private javax.swing.JPanel updateSubjectPanel;
    private javax.swing.JPanel uploadVideoPanel;
    // End of variables declaration//GEN-END:variables
}
